.TH MYSTRLEN 3 "September 2026" "OS Assignment 01" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B int mystrlen(const char *s);
.SH DESCRIPTION
The
.B mystrlen
function calculates the number of characters in the string
.I s
before the terminating null character.
.SH AUTHOR
Subhan Ahmad
