.TH MYSTRNCPY 3 "September 2026" "OS Assignment 01" "Library Functions"
.SH NAME
mystrncpy \- copy up to a specified number of characters
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B int mystrncpy(char *dest, const char *src, int n);
.SH DESCRIPTION
The
.B mystrncpy
function copies characters from
.I src
to
.I dest
until either the null character is reached or
.I n
characters have been copied.
It returns the number of characters copied.
.SH AUTHOR
Subhan Ahmad
