.TH MYSTRCAT 3 "September 2026" "OS Assignment 01" "Library Functions"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B int mystrcat(char *dest, const char *src);
.SH DESCRIPTION
The
.B mystrcat
function appends the string pointed to by
.I src
to the end of the string pointed to by
.I dest
and adds a terminating null character.
It returns the length of the resulting string.
.SH AUTHOR
Subhan Ahmad
